"""Add is_active to User and ADMIN/STAFF to RoleEnum

Revision ID: 21b30b9f4f92
Revises: f181819ee6e7
Create Date: 2026-09-21 09:57:55.287335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b30b9f4f92'
down_revision: Union[str, Sequence[str], None] = 'f181819ee6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # Note: Enums need manual alteration in Postgres. We add IF NOT EXISTS to be safe, but typically postgres >= 9.1 supports ADD VALUE.
    # We must commit before altering type if we were in a transaction block, but alembic autogenerate doesn't handle enums natively well.
    # The safest way is direct execution with commit.
    op.execute("COMMIT")
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'ADMIN'")
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'STAFF'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
