"""Add content_hash

Revision ID: 5534dfcdd5b8
Revises: 8da3e2aa386a
Create Date: 2026-09-23 11:01:07.715874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5534dfcdd5b8'
down_revision: Union[str, Sequence[str], None] = '8da3e2aa386a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_versions_content_hash'), 'document_versions', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_content_hash'), table_name='document_versions')
    op.drop_column('document_versions', 'content_hash')
    # ### end Alembic commands ###
