"""Add processing status

Revision ID: 70f27e979825
Revises: 709ae459d923
Create Date: 2026-09-17 11:04:55.102074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f27e979825'
down_revision: Union[str, Sequence[str], None] = '709ae459d923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    processing_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatusenum')
    processing_status_enum.create(op.get_bind())
    op.add_column('document_versions', sa.Column('processing_status', processing_status_enum, nullable=False, server_default='PENDING'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'processing_status')
    # ### end Alembic commands ###
